# name字段是 workflow 的名称。
# 如果省略该字段，默认为当前 workflow 的文件名。
name: tea-blog

# on字段指定触发 workflow 的条件，通常是某些事件。
on:
  # push事件触发 workflow
  push:
    # 只有master分支发生push事件时，才会触发 workflow
    branches: 
      - master
  # 手动触发部署
  # workflow_dispatch:

# workflow 文件的主体是jobs字段，表示要执行的一项或多项任务。

jobs:
  tea-blog-1:
  # 指定运行所需要的虚拟机环境。（必填字段）
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        # 选择要使用的 node 版本
        node-version: '14'
    - name: Install npm
      run: npm install
      # 运行构建脚本
    - name: Build VuePress site
      run: npm start

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

